apiVersion: v1
kind: Service
metadata:
  name: fhem
  labels:
    app: fhem
    group: iot
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 8083
    targetPort: 8083
    protocol: TCP
  selector:
    app: fhem
    group: iot
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: fhem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fhem
      group: iot
      tier: frontend
  template:
    metadata:
      labels:
        app: fhem
        group: iot
        tier: frontend
    spec:
      containers:
      - name: fhem
        image: marcel1691/fhem
        ports:
        - containerPort: 8083